# Benchmark Config
dataset: 
  name: "ModelNet10"
  object_idx_limit: 100

# Numpy and Torch Seed
random_seed: 0

# Universal Object Settings
object_settings:
  number_views: &number_views 4
  min_angle: 0
  max_angle: 360
  number_points: 1000
  number_rendered_points: 250
  scaling_mode: &scaling_mode "rendering" # To enforce same number of points for all objects
  adapt_number_points: False
  verbose: False

# Rendering Settings
camera:
  scale: 1
  image_height: 500
  image_width: 500
  fx: 250
  fy: 250

# Object Collection Settings
epsilon: 0.5 #For Overlap Calculation , 10 meter rendering, 1m is 0.05
fps: False # Furthest Point Sampling
noise_std: 0.1
pose_estimation: kabsch # kabsch, icp, ----> icp_kabsch to be implemented

object_collection:
  number_collections: 2
  excluded_classes:
          # - "bed"
          # - "chair"
          # - "sofak"
          # - "table"

  object_collection_sampler:
    type: "interclass" # interclass, intraclass TODO: Add intraclass
    index_selection: "sequential" # random, sequential
        
  object_collection_settings:
    object_scaling_mode: *scaling_mode
    number_views: *number_views
    lhs_mode: "tracked" # scan, tracked, mesh
    rhs_mode: "full_tracked" # next_scan, mesh, full_tracked
    
# Plot Settings
plot_per_class: True
save_plots: True # Either Plot or Save
save_dir: "results/t"


# NOTE: Currently idenetity rotation is used for all objects
# TODO: Add noise to the pointclouds